### ISSUE TITLE
Setting HTTP headers when using MQTT over WebSocket

### ISSUE THREAD

**Issue by a-backman** [brocaar/chirpstack-gateway-bridge#133]
### Is this a bug or a feature request?
Feature request

Hi,
Would it be possible to add the ability to set HTTP headers when connecting to MQTT over WebSocket? I noticed that you are using the Paho MQTT client which supports this. (https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L85)

I have a use-case where I'm connecting to the MQTT-broker through a generic WebSocket proxy that does not speak MQTT. Here I would like to let the proxy handle the authentication by looking at a HTTP header.

**Comment by brocaar** [comment]
I'm closing this issue. I do understand that there could be an use-case for this, but this looks really specific to me and this issue hasn't seen any other interest. I would like to avoid adding too much configuration, I hope you understand. Of course you could always create a custom build for your use-case :)
