### ISSUE TITLE
tokenMap is unlimited

### ISSUE THREAD

**Issue by orientlu** [brocaar/chirpstack-gateway-bridge#143]
### Is this a bug or a feature request?
![image](https://user-images.githubusercontent.com/6871867/68006213-d043e700-fcb2-11e9-8d82-627c6d145372.png)

**Comment by brocaar** [comment]
It is limited to `uint16` items, it is not unlimited. I think this either this uses a limited amount of memory or a kind of garbage collector logic is needed so this would require more CPU. In the correct version I have chosen to rely on a bit of RAM as the note states.
