### ISSUE TITLE
NetId filter with basicstation

### ISSUE THREAD

**Issue by istina-iot** [brocaar/chirpstack-gateway-bridge#157]
### Is this a bug or a feature request?
Bug: bridge or basicstation?
### What did you expect?
Filtering packets by NetId for custom NetId numbers or filtering disable, according to bridge config
### What happened?
all packets always filtered by `NET ID=000000`
### What version are your using?
`3.6`
### How can your issue be reproduced?
Try filters any net with basicstation, except `000000` and try run bridge without filtering
### Could you share your log output?
bridge logs:
```
INFO[0000] starting ChirpStack Gateway Bridge            docs="https://www.chirpstack.io/gateway-bridge/" version=3.6.0
INFO[0000] filters: NetID filter configured              net_id=000000
```
bridge config:
```
cat ./chirpstack-gateway-bridge.toml | grep net_ids
net_ids=["888888"]
```
basicstation log:
```
2020-01-17 09:52:38.220 [S2E:VERB]   NetID filter: 00000001-00000001-00000001-00000001
```

**Comment by brocaar** [comment]
Thanks, this should be fixed with the above commit.
