### ISSUE TITLE
Missing CRL file when installing Gateway bridge

### ISSUE THREAD

**Issue by MainManu** [brocaar/chirpstack-gateway-bridge#167]
### Is this a bug or a feature request?
This issue is neither, it probably is a server configuration error.

### What did you expect?
I expected to install the gateway bridge using ```sudo apt-get install lora gateway bridge``` after setting up the required repository.

### What happened?
I received the following error message after running ```sudo apt update```: 
```W: Failed to fetch https://artifacts.chirpstack.io/packages/3.x/deb/dists/stable/main/binary-armhf/Packages server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none```

###What version are you using?
I am using a headless raspian image provided by IMST for their Lora lite gateway.

**Comment by brocaar** [comment]
This looks like a server configuration issue. See also: https://www.google.com/search?client=firefox-b-d&q=%22CAfile%3A+%2Fetc%2Fssl%2Fcerts%2Fca-certificates.crt+CRLfile%3A+none%22.
