### ISSUE TITLE
Geoloc position of gateways in uplink packets

### ISSUE THREAD

**Issue by NICOLASGON** [brocaar/chirpstack-gateway-bridge#173]
Hello,
With my colleagues we are not sure but we remember that the gateway bridge added geoloc meta-data (static not with a gps on gateway) that we set up in the UI in all uplink packets. Since we upgraded to Chirpstack we don't have this feature anymore.

Are we correct or our memory is failing us ?

Thank you for your help,
ngonzalez

**Comment by brocaar** [comment]
I'm not really sure about what you mean....
