### ISSUE TITLE
Configure Packet Forwarder for LG01-N for Azure IoT Hub

### ISSUE THREAD

**Issue by vermaaditya** [brocaar/chirpstack-gateway-bridge#175]
Hi Team, 

I am willing to integrate the LoRa with the Azure IoT Hub using the documentation provided on - https://www.chirpstack.io/project/guides/microsoft-azure. 

As a part of this we are supposed to configure and install packet forwarder, so for that I am following the link - https://www.chirpstack.io/gateway-bridge/gateway/dragino/. I did the installation and configured my gateway with the Device Connection string which is provisioned in the Azure IoT hub, but i don't see any messages coming thru and being published. 

Please help in finding where am I missing. Nothing is coming on the logs as well.

The same gateway works fine with using with TTN.

Appreciate your prompt response. 

Thanks,

**Comment by brocaar** [comment]
Please see https://www.chirpstack.io/project/guides/troubleshooting/gateway/. I'm going to close this issue. For bug reports and feature requests, please use the provided template. It contains a couple of essential questions that must be answered which helps the community to respond.
