### ISSUE TITLE
New Azure IoT root CAs

### ISSUE THREAD

**Issue by jburhenn** [brocaar/chirpstack-gateway-bridge#178]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-bridge) of this repository and believe that this is not a duplicate.

## Summary

According to [this Microsoft announcement](https://techcommunity.microsoft.com/t5/internet-of-things/azure-iot-tls-changes-are-coming-and-why-you-should-care/ba-p/1658456) they are updating TLS certs on their servers. It looks like the chirpstack-gateway-bridge doesn't require any changes for now but they seem to suggest pinning a couple new roots in addition to the Baltimore Root CA in order to prevent possible future issues.

> To continue without disruption due to this change, Microsoft recommends that client applications or devices pin the Baltimore root -
> Baltimore Root CA
> (Thumbprint: d4de20d05e66fc53fe1a50882c78db2852cae474)
> To prevent future disruption, client applications or devices should also pin the following roots:
> Microsoft RSA Root Certificate Authority 2017
> (Thumbprint: 73a5e64a3bff8316ff0edccc618a906e4eae4d74)
> Digicert Global Root G2
> (Thumbprint: df3c24f9bfd666761b268073fe06d1cc8d4f82a4)

## What is the use-case?

Future proofing Azure IoT connections.

## Implementation description

Simplest implementation would be to add the new certs to the certpool in azure_iot_hub.go.

## Can you implement this by yourself and make a pull request?

Yes.

**Comment by brocaar** [comment]
If you could make an PR for this, that would be much appreciated :)
