### ISSUE TITLE
Rest API CreateKeys method

### ISSUE THREAD

**Issue by medalist1981** [brocaar/chirpstack-gateway-bridge#186]
the appKey parameter writes not the right value. Instead of appKey the nwkKey is writing the value into the appKey field.

**Comment by brocaar** [comment]
I think this was meant for the chirpstack-application-server repo. However, please note that this behavior is correct. Please refer to the documentation of the fields for this API. It is confusing, but it is because of a rename that took place in the LoRaWAN 1.1.x specs.
