### ISSUE TITLE
Allow for using port 80 on Basics Station

### ISSUE THREAD

**Issue by gbird3** [brocaar/chirpstack-gateway-bridge#188]
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-bridge) of this repository and believe that this is not a duplicate.

## Summary

I should be able to use port 80 for BasicsStation.

## What is the use-case?

Using a common port like port 80 allows for easier setup and limits the amount of firewall changes needed.

## Implementation description

Currently you can't use port 80 because the request.Host drops the port if it is port 80. It is as simple as checking if the host has a port and if not, add port 80.

## Can you implement this by yourself and make a pull request?

Yes. I have code I am testing that implements this.

**Comment by brocaar** [comment]
I'm closing this, please see my comment on: https://github.com/brocaar/chirpstack-gateway-bridge/pull/189.
