### ISSUE TITLE
sx1302 fine timestamp shows NONE

### ISSUE THREAD

**Issue by sagar-patel-sls** [brocaar/chirpstack-gateway-bridge#193]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/brocaar/chirpstack-gateway-bridge) of this repository and believe that this is not a duplicate.

## What happened?
https://github.com/Lora-net/sx1302_hal
we are using `sx1302_hal` for our Semtech v2 gateway but we are not getting `FineTimeStamp`.

Please find below our packet forwarder `rxpk `logs. Packet Forwarder sending fine timestamp in `ftime` property.

## Could you share your log output?

```shell
{
  "rxpk": [
    {
      "jver": 1,
      "tmst": 61957276,
      "time": "2021-06-03T12:30:13.998891Z",
      "tmms": 1306758632999,
      "ftime": 286852861,
      "chan": 2,
      "rfch": 1,
      "freq": 865.985,
      "mid": 1,
      "stat": 1,
      "modu": "LORA",
      "datr": "SF12BW125",
      "codr": "4/5",
      "rssis": -115,
      "lsnr": 1.5,
      "foff": 11527,
      "rssi": -113,
      "size": 37,
      "data": "QC9PxwEAAwACjIh/7i3tan9C0TB+RTEMPAuJxCcbWnKF/t+tEw=="
    }
  ]
}
```
![sx1302-gw-logs](https://user-images.githubusercontent.com/43664335/120745708-5a9d9e00-c51b-11eb-8472-c99acb7dc345.png)

## Your Environment

| Component           | Version |
| --------------------| ------- |
| Application Server  | v3.15.0  |
| Network Server      | v3.13.0  |
| Gateway Bridge      | v3.11.0 |

**Comment by brocaar** [comment]
The above commit adds the parsing of the `ftime` field. Could you confirm if this solves your issue?
