### ISSUE TITLE
Request for doc/code/ which convert MQTT Json Downlink JSON to Semtech Downlink Json(UDP) Format

### ISSUE THREAD

**Issue by mightChamp** [brocaar/chirpstack-gateway-bridge#200]
Hello,

I am using chripstack on my server, My gateway is custom made gateway, I want to use MQTT protocol rather than Semtech UDP Packet Forwarder. I get success in uplinks using MQTT packet structure as mentioned here. But In downlink, json packet, some parameters are missing comapred to semtech udp downlink packet.

Semtech Downlink Json:
{“txpk”:{
“imme”:true,
“freq”:864.123456,
“rfch”:0,
“powe”:14,
“modu”:“LORA”,
“datr”:“SF11BW125”,
“codr”:“4/6”,
“ipol”:false,
“size”:32,
“ncrc”:true,
“data”:“H3P3N2i9qc4yt7rK7ldqoeCVJGBybzPY5h1Dd7P7p8v”
}}

Chripstack MQTT Downlink Json :

{
“phyPayload”:“YGcsBACQAAAAGzv2H29bigkqF3roPD1jQ5tyAJkJqZIn09HH”,
“txInfo”:{
“gatewayID”:“fJ69z///vKA=”,
“frequency”:865062500,
“power”:27,
“modulation”:“LORA”,
“loRaModulationInfo”:{
“bandwidth”:125,
“spreadingFactor”:12,
“codeRate”:“4/5”,
“polarizationInversion”:true
},
“board”:0,
“antenna”:0,
“timing”:“DELAY”,
“delayTimingInfo”:{
“delay”:“1s”
},
“context”:null
},
“token”:14831,
“downlinkID”:“Oe9C1x0dSkKLZO2gMwmpGw==”,
“items”:[
{
“phyPayload”:“YGcsBACQAAAAGzv2H29bigkqF3roPD1jQ5tyAJkJqZIn09HH”,
“txInfo”:{
“gatewayID”:null,
“frequency”:865062500,
“power”:27,
“modulation”:“LORA”,
“loRaModulationInfo”:{
“bandwidth”:125,
“spreadingFactor”:12,
“codeRate”:“4/5”,
“polarizationInversion”:true
},
“board”:0,
“antenna”:0,
“timing”:“DELAY”,
“delayTimingInfo”:{
“delay”:“1s”
},
“context”:null
}
},
{
“phyPayload”:“YGcsBACQAAAAGzv2H29bigkqF3roPD1jQ5tyAJkJqZIn09HH”,
“txInfo”:{
“gatewayID”:null,
“frequency”:866550000,
“power”:27,
“modulation”:“LORA”,
“loRaModulationInfo”:{
“bandwidth”:125,
“spreadingFactor”:10,
“codeRate”:“4/5”,
“polarizationInversion”:true
},
“board”:0,
“antenna”:0,
“timing”:“DELAY”,
“delayTimingInfo”:{
“delay”:“2s”
},
“context”:null
}
}
],
“gatewayID”:“fJ69z///vKA=”
}

Missing Parameter in Chripstack MQTT JSON Data:

timestamp to transmit data
RF Chain to be use
Data Size
CRC
I cannot use chripstack gateway bridge to convert MQTT to semtech UDP packet format, as only want to use MQTT. So, I need help to get missing data information.

How gateway bridge code converts MQTT JSON format to UDP format?
How can I get 4 missing parameter from MQTT JSON data?

Thank You

**Comment by brocaar** [comment]
> How gateway bridge code converts MQTT JSON format to UDP format?

I'm closing this issue as this is more of a consultancy question than bug report or feature request. Please consult the source-code, you will find everything in this repository.
