### ISSUE TITLE
allow multiple mqtt brokers & InsecureSkipVerify flag with ssl config

### ISSUE THREAD

**Issue by kushal154** [brocaar/chirpstack-gateway-bridge#93]
### Is this a bug or a feature request?
Feature Request

### What did you expect?
1) I want to setup multiple mqtt brokers. As per current config file, it accepts only one.
2) I want to have allow mqtt over ssl when host is IP address and not domain.

### What version are your using?
master

### How can your issue be reproduced?
If I try to do ssl over mqtt with server="ssl://192.168.0.104:8883", it gives an error.

> ERRO[0000] could not setup mqtt backend, retry in 2 seconds: Network Error : x509: cannot validate certificate for 192.168.0.104 because it doesn't contain any IP SANs 

I have created a patch which is working for me. Can you please incorporate the changes and make it available in next point release.
[lora-gateway-bridge-patch.txt](https://github.com/brocaar/lora-gateway-bridge/files/2423132/lora-gateway-bridge-patch.txt)

**Comment by kushal154** [comment]
I think we can keep InsecureSkipVerify as configurable parameter in toml. By default, it is false with an option to change it to true. That way we can leave it for end user to decide.

On the multiple MQTT brokers, we can consider either of the 2 ways. There are enough open client libraries following one or the other approach. I think its just the matter of choice.

**Comment by brocaar** [comment]
I'm closing this issue. #141 implemented the multiple MQTT broker option. With regards to the certificate issue, I think it is better / safer to make sure the MQTT server is resolvable by the CN as configured in the certificate. This means either configure the hostname properly or update the certificate of your MQTT broker.
